workflows:
  CICdDemo-worldflow:
    name: CICdDemo
    scripts:
        - name: Started
          script: echo "Welcome to your CICD"
        - name: Build CICdDemo
          script: - xcodebuild build -workspace "CICdDemo.xcworkspace" -scheme "CICdDemo" CODE_SIGN_INDENTITY="iPhone Distribution" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
 
